### ISSUE TITLE
CutMesh

### ISSUE THREAD

**Issue by xiaodongdong101** [MeshInspector/MeshInspector#111] opened 2023-06-29 02:04 UTC
If I input ordered points(The points are not in the same plane), first I want to project the points onto the surface of the model, secondly cut the grid model through the connection between points, and finally I want to fill the cut surface with a new surface.
1.I need to intercept this contour line on the  model
2.I need to cutmesh by this contour(The contour points are not in the same plane)

**Comment by Grantim** [comment] 2023-06-29 08:14
This Issue is MeshLib related (duplicate of https://github.com/MeshInspector/MeshLib/issues/1374)

**Closed by Grantim** 2023-06-29 08:14 UTC
