### ISSUE TITLE
Flashback after using face selector

### ISSUE THREAD

**Issue by BlackantHermit** [MeshInspector/MeshInspector#88] opened 2022-12-22 03:06 UTC
I opened an stl model today and tried to use the `Face selector` and select some triangles in default mode. But the software always crashes after drawing the line.
I used the `.msi` installation package to `repair` the software, it was fine once, and then it started to crash again.

**Comment by BlackantHermit** [comment] 2022-12-22 03:10
The `single face` mode is good, and I feel like there is a problem after drawing the line.

**Comment by Fedr** [comment] 2022-12-22 07:03
Thanks for your report. Very strange indeed. Could you please attach MeshInpsector log after the crash happens?

**Comment by BlackantHermit** [comment] 2022-12-22 08:23
> Thanks for your report. Very strange indeed. Could you please attach MeshInspector log after the crash happens?

[22/12/22 16:18:20.972] [info] MR Version info: 0.0.128.21
[22/12/22 16:18:21.781] [info] Log file: C:\Users\yzq-01\AppData\Local\Temp\MeshInspector\Logs\MRLog_2022-12-22_16-18-20_42.txt
[22/12/22 16:18:21.781] [info] Try sign in.
[22/12/22 16:18:22.276] [info] OpenGL Version 4.3 loaded
[22/12/22 16:18:22.276] [info] OpenGL version received: 4.3.0
[22/12/22 16:18:22.276] [info] Supported OpenGL is 4.3.0 NVIDIA 517.00
[22/12/22 16:18:22.276] [info] Supported GLSL is 4.30 NVIDIA via Cg compiler
[22/12/22 16:18:22.279] [info] Not found any attached SpaceMouse
[22/12/22 16:18:22.280] [info] Init menu plugin.
[22/12/22 16:18:22.281] [info] Splash window thread started
[22/12/22 16:18:22.549] [info] System info:
{
	"CPU Info" : 
	{
		"CPU" : "12th Gen Intel(R) Core(TM) i7-12700H",
		"Concurrent threads" : 20
	},
	"Memory Info" : 
	{
		"Physical memory available" : "5.8 GB",
		"Physical memory total" : "15.7 GB",
		"Virtual memory available" : "13.7 GB",
		"Virtual memory total" : "29.2 GB"
	},
	"OpenGL Info" : 
	{
		"OpenGL Version" : "4.3.0 NVIDIA 517.00",
		"Renderer" : "NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2",
		"Vendor" : "NVIDIA Corporation"
	},
	"Version" : "0.0.128.21",
	"Window Info" : 
	{
		"Framebuffer size" : "1280 x 800",
		"Menu scaling" : "1.75",
		"Pixel ratio" : "1",
		"System scaling" : "1.75",
		"Window size" : "1280 x 800"
	}
}

[22/12/22 16:18:22.559] [info] Load user settings.
[22/12/22 16:18:22.559] [info] Setup dark color theme.
[22/12/22 16:18:22.560] [info] Apply color theme.
[22/12/22 16:18:23.182] [info] Signed in.
[22/12/22 16:18:27.283] [info] Splash window thread finished
[22/12/22 16:18:27.292] [info] Resize window: 2560 1406
[22/12/22 16:18:27.457] [info] Set window pos: 0 40
[22/12/22 16:18:27.465] [info] Maximize window.
[22/12/22 16:18:27.484] [info] Set menu plugin scene window size: 600 1207
[22/12/22 16:18:48.454] [info] Loading file D:\code\repos\remInput\webcam_housing.stl
[22/12/22 16:18:48.465] [info] Load file D:\code\repos\remInput\webcam_housing.stl - success
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.655] [critical] Crash signal: 11
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.654] [critical] Crash signal: 11
[22/12/22 16:19:01.656] [critical] Crash signal: 11
[22/12/22 16:19:02.515] [critical] Crash stacktrace:
 0# MR::Logger::getLogFileName in MRMesh
 1# MR::Logger::addSink in MRMesh
 2# log2f in ucrtbase
 3# _intrinsic_setjmpex in ucrtbase
 4# _C_specific_handler in ucrtbase
 5# _C_specific_handler_noexcept in ucrtbase
 6# _chkstk in ntdll
 7# RtlFindCharInUnicodeString in ntdll
 8# KiUserExceptionDispatcher in ntdll
 9# MR::SaveOnClosePlugin::shutdown in MRViewer
10# MR::findVertsInViewportArea in MRViewer
11# MR::SaveOnClosePlugin::shutdown in MRViewer
12# MR::SaveOnClosePlugin::shutdown in MRViewer
13# MR::SelectScreenLasso::calculateSelectedPixels in MRViewer
14# tbb::detail::r1::isolate_within_arena in tbb12
15# tbb::detail::r1::is_tbbmalloc_used in tbb12
16# tbb::detail::r1::global_control_active_value in tbb12
17# tbb::detail::r1::set_end_of_input in tbb12
18# tbb::detail::r1::set_end_of_input in tbb12
19# recalloc in ucrtbase
20# BaseThreadInitThunk in KERNEL32
21# RtlUserThreadStart in ntdll

[22/12/22 16:19:02.616] [info] Progress thread time tree (min printed time 0.1 sec):
[22/12/22 16:19:02.616] [info]     Count        Time   Self time    Name
[22/12/22 16:19:02.616] [info]         1      14.162      14.152    (total)
[22/12/22 16:19:02.616] [info] 
[22/12/22 16:19:02.616] [info] Slowest places:
[22/12/22 16:19:02.616] [info]     Count   Self time    Name
[22/12/22 16:19:02.616] [info]         1      14.152    (other)
[22/12/22 16:19:02.616] [info] Skip places faster than 0.1 sec
[22/12/22 16:19:02.616] [warning] Mesh shader is not freed
[22/12/22 16:19:02.616] [warning] Picker shader is not freed
[22/12/22 16:19:02.616] [warning] Mesh border shader is not freed
[22/12/22 16:19:02.616] [warning] Labels shader is not freed
[22/12/22 16:19:02.616] [warning] Viewport border shader is not freed
[22/12/22 16:19:02.618] [info] Saving config file: C:\Users\yzq-01\AppData\Roaming\MeshInspector\config.json
[22/12/22 16:19:02.620] [info] Main thread time tree (min printed time 0.1 sec):
[22/12/22 16:19:02.620] [info]     Count        Time   Self time    Name
[22/12/22 16:19:02.620] [info]         1      41.658      41.629    (total)
[22/12/22 16:19:02.620] [info] 
[22/12/22 16:19:02.620] [info] Slowest places:
[22/12/22 16:19:02.620] [info]     Count   Self time    Name
[22/12/22 16:19:02.620] [info]         1      41.629    (other)
[22/12/22 16:19:02.620] [info] Skip places faster than 0.1 sec

**Comment by BlackantHermit** [comment] 2022-12-22 08:24
> Thanks for your report. Very strange indeed. Could you please attach MeshInspector log after the crash happens?

I pasted the log, hope that helps you.

**Comment by Fedr** [comment] 2022-12-22 08:42
Thanks for the log. Is the issue reproducible with any mesh? If not, could please attach your mesh packed in .zip?

**Comment by Grantim** [comment] 2022-12-22 16:33
Can you please try https://drive.google.com/file/d/1C9eC3lR_E-PhBTU45b3kSY6DU4JlDqQn/view?usp=share_link this build (it has more symbols) and send log pls

**Comment by BlackantHermit** [comment] 2022-12-23 02:30
> 

I currently have this problem with any mesh I use. But when it was first installed this function was working fine. It's amazing.

**Comment by BlackantHermit** [comment] 2022-12-23 02:31
> Thanks for the log. Is the issue reproducible with any mesh? If not, could please attach your mesh packed in .zip?

I currently have this problem with any mesh I use. But when it was first installed this function was working fine. It's amazing.

**Comment by BlackantHermit** [comment] 2022-12-23 02:38
> Can you please try [this](https://drive.google.com/file/d/1C9eC3lR_E-PhBTU45b3kSY6DU4JlDqQn/view?usp=share_link) build (it has more symbols) and send log pls

[23/12/22 10:33:20.929] [info] MR Version info: 0.0.128.21
[23/12/22 10:33:22.306] [info] Log file: C:\Users\yzq-01\AppData\Local\Temp\MeshInspector\Logs\MRLog_2022-12-23_10-33-20_81.txt
[23/12/22 10:33:22.306] [info] Try sign in.
[23/12/22 10:33:22.803] [info] OpenGL Version 4.3 loaded
[23/12/22 10:33:22.803] [info] OpenGL version received: 4.3.0
[23/12/22 10:33:22.803] [info] Supported OpenGL is 4.3.0 NVIDIA 517.00
[23/12/22 10:33:22.803] [info] Supported GLSL is 4.30 NVIDIA via Cg compiler
[23/12/22 10:33:22.806] [info] Not found any attached SpaceMouse
[23/12/22 10:33:22.807] [info] Init menu plugin.
[23/12/22 10:33:22.808] [info] Splash window thread started
[23/12/22 10:33:23.046] [info] System info:
{
	"CPU Info" : 
	{
		"CPU" : "12th Gen Intel(R) Core(TM) i7-12700H",
		"Concurrent threads" : 20
	},
	"Memory Info" : 
	{
		"Physical memory available" : "5.7 GB",
		"Physical memory total" : "15.7 GB",
		"Virtual memory available" : "15.7 GB",
		"Virtual memory total" : "29.2 GB"
	},
	"OpenGL Info" : 
	{
		"OpenGL Version" : "4.3.0 NVIDIA 517.00",
		"Renderer" : "NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2",
		"Vendor" : "NVIDIA Corporation"
	},
	"Version" : "0.0.128.21",
	"Window Info" : 
	{
		"Framebuffer size" : "1280 x 800",
		"Menu scaling" : "1.75",
		"Pixel ratio" : "1",
		"System scaling" : "1.75",
		"Window size" : "1280 x 800"
	}
}

[23/12/22 10:33:23.052] [info] Load user settings.
[23/12/22 10:33:23.052] [info] Setup dark color theme.
[23/12/22 10:33:23.052] [info] Apply color theme.
[23/12/22 10:33:23.491] [info] Signed in.
[23/12/22 10:33:27.836] [info] Splash window thread finished
[23/12/22 10:33:27.849] [info] Resize window: 2560 1406
[23/12/22 10:33:28.122] [info] Set window pos: 0 40
[23/12/22 10:33:28.130] [info] Maximize window.
[23/12/22 10:33:28.167] [info] Set menu plugin scene window size: 600 1207
[23/12/22 10:33:32.289] [info] Loading file C:\Users\yzq-01\Desktop\1180背包卡扣_外壳      20.stl
[23/12/22 10:33:32.307] [info] Load file C:\Users\yzq-01\Desktop\1180背包卡扣_外壳      20.stl - success
[23/12/22 10:34:12.860] [critical] Crash signal: 11
[23/12/22 10:34:12.860] [critical] Crash signal: 11
[23/12/22 10:34:13.156] [critical] Crash stacktrace:
 0# MR::Logger::getLogFileName in MRMesh
 1# MR::Logger::addSink in MRMesh
 2# log2f in ucrtbase
 3# _intrinsic_setjmpex in ucrtbase
 4# _C_specific_handler in ucrtbase
 5# _C_specific_handler_noexcept in ucrtbase
 6# _chkstk in ntdll
 7# RtlFindCharInUnicodeString in ntdll
 8# KiUserExceptionDispatcher in ntdll
 9# MR::SaveOnClosePlugin::shutdown in MRViewer
10# MR::SaveOnClosePlugin::shutdown in MRViewer
11# MR::SaveOnClosePlugin::shutdown in MRViewer
12# MR::SelectScreenLasso::calculateSelectedPixels in MRViewer
13# tbb::detail::r1::isolate_within_arena in tbb12
14# tbb::detail::r1::is_tbbmalloc_used in tbb12
15# tbb::detail::r1::global_control_active_value in tbb12
16# tbb::detail::r1::set_end_of_input in tbb12
17# tbb::detail::r1::set_end_of_input in tbb12
18# recalloc in ucrtbase
19# BaseThreadInitThunk in KERNEL32
20# RtlUserThreadStart in ntdll

[23/12/22 10:34:13.250] [info] Progress thread time tree (min printed time 0.1 sec):
[23/12/22 10:34:13.250] [info]     Count        Time   Self time    Name
[23/12/22 10:34:13.250] [info]         1      40.961      40.944    (total)
[23/12/22 10:34:13.250] [info] 
[23/12/22 10:34:13.250] [info] Slowest places:
[23/12/22 10:34:13.250] [info]     Count   Self time    Name
[23/12/22 10:34:13.250] [info]         1      40.944    (other)
[23/12/22 10:34:13.250] [info] Skip places faster than 0.1 sec
[23/12/22 10:34:13.250] [warning] Mesh shader is not freed
[23/12/22 10:34:13.251] [warning] Picker shader is not freed
[23/12/22 10:34:13.251] [warning] Mesh border shader is not freed
[23/12/22 10:34:13.251] [warning] Points shader is not freed
[23/12/22 10:34:13.251] [warning] Lines shader is not freed
[23/12/22 10:34:13.251] [warning] Labels shader is not freed
[23/12/22 10:34:13.251] [warning] Viewport border shader is not freed
[23/12/22 10:34:13.253] [info] Saving config file: C:\Users\yzq-01\AppData\Roaming\MeshInspector\config.json
[23/12/22 10:34:13.256] [info] Main thread time tree (min printed time 0.1 sec):
[23/12/22 10:34:13.256] [info]     Count        Time   Self time    Name
[23/12/22 10:34:13.256] [info]         1      52.336      51.783    (total)
[23/12/22 10:34:13.256] [info]       235       0.369       0.369        MR::Viewport::multiPickObjects
[23/12/22 10:34:13.256] [info] 
[23/12/22 10:34:13.256] [info] Slowest places:
[23/12/22 10:34:13.256] [info]     Count   Self time    Name
[23/12/22 10:34:13.256] [info]         1      51.783    (other)
[23/12/22 10:34:13.256] [info]       248       0.404    MR::Viewport::multiPickObjects
[23/12/22 10:34:13.256] [info] Skip places faster than 0.1 sec

**Comment by BlackantHermit** [comment] 2022-12-23 02:57
> Can you please try [this](https://drive.google.com/file/d/1C9eC3lR_E-PhBTU45b3kSY6DU4JlDqQn/view?usp=share_link) build (it has more symbols) and send log pls

I used the installer you sent, and I'm having the problem again of flickering after drawing lines in the face selector switching between different modes. Above is the log.

**Comment by Grantim** [comment] 2022-12-23 09:51
Thanks for new data. Also can you please provide your `%appdata%\MeshInspector\config.json` file, and record a video with crash please. Unfortunately we cannot reproduce it on our side.

**Comment by BlackantHermit** [comment] 2022-12-23 12:34
> Thanks for new data. Also can you please provide your `%appdata%\MeshInspector\config.json` file, and record a video with crash please. Unfortunately we cannot reproduce it on our side.

I sent the file to your email address with the subject Face Selector Bug Info.

**Comment by Grantim** [comment] 2023-01-30 05:47
Hi, as far this issue is not reproducing anymore we are closing the issue. Please reopen it if you will face same problem again.

**Closed by Grantim** 2023-01-30 05:47 UTC
